#server:
#  port:
#    9093
#spring:
#  spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/minet_bc_128_transaction
#      driver-class: com.mysql.cj.jdbc.Driver
#      username: root
#      password: SandyZemosoID@1
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
#      database: mysql
#      database-platform: org.hibernate.dialect.MySQLDialect
#  application:
#    name: PORTFOLIO-SERVICE
#  flyway:
#    baseline-on-migration: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 1
#    locations: classpath:db/migration
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    instance: localhost